name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.10'
  POSTGRES_URL: 'postgresql://postgres:postgres@localhost:5432/test_db'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-driver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov psycopg2-binary selenium

      - name: Configure environment
        run: |
          echo "CHROMEDRIVER_PATH=/usr/bin/chromedriver" >> $GITHUB_ENV
          echo "DISPLAY=:99" >> $GITHUB_ENV
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            sleep 2
          done

      - name: Run tests
        env:
          POSTGRES_URL: ${{ env.POSTGRES_URL }}
          DISPLAY: ${{ env.DISPLAY }}
          CHROMEDRIVER_PATH: ${{ env.CHROMEDRIVER_PATH }}
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          pytest -v --cov=./ --cov-report=xml tests/

      - name: Upload coverage
        if: always()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: false
