name: Dealscout E-commerce PriceTracker CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.10'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov psycopg2-binary

      - name: Install Chrome for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver
          export PATH=$PATH:/usr/local/bin

      - name: Run tests
        env:
          POSTGRES_URL: "postgresql://postgres:postgres@localhost:5432/test_db"
          DISPLAY: ":99"
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          timeout 20s bash -c 'until pg_isready -h localhost -p 5432; do sleep 1; done'
          pytest --cov=./ tests/

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
