name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.10'
  POSTGRES_URL: 'postgresql://postgres:postgres@localhost:5432/test_db'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov psycopg2-binary selenium

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            sleep 2
          done

      - name: Run tests
        env:
          DISPLAY: ":99"
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          export PATH=$PATH:/usr/lib/chromium-browser/
          pytest --cov=./ --cov-report=xml --cov-report=term --durations=5 -v tests/

      - name: Validate coverage file
        run: |
          ls -la
          [ -f coverage.xml ] || exit 1
          echo "Coverage file exists with size: $(wc -c < coverage.xml) bytes"

      - name: Upload to Codecov (Bash method)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          # Method 1: Direct curl upload
          curl -s https://codecov.io/bash | bash -s -- -t $CODECOV_TOKEN -f coverage.xml -n "GitHub Actions" -F unittests -v
          
          # Alternative method if above fails
          # pip install codecov
          # python -m codecov --token=$CODECOV_TOKEN --file=coverage.xml
